// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TazedirektsonAPI.Persistence.Contexts;

namespace TazedirektsonAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200603153807_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("VatanAPI.Core.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("VatanAPI.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "aydemir@gmail.com",
                            LastName = "Aydemir",
                            Name = "Emre",
                            Password = "1234",
                            UserName = "AydemirEmre"
                        },
                        new
                        {
                            Id = 2,
                            Email = "akdeniz@gmail.com",
                            LastName = "Akdeniz",
                            Name = "Yusuf",
                            Password = "4567",
                            UserName = "AkdenizYusuf"
                        });
                });

            modelBuilder.Entity("VatanAPI.Core.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "Telefon"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Bilgisayar"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Bilgisayar Parçaları"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Kamera"
                        },
                        new
                        {
                            Id = 104,
                            Name = "TV & Ev Elektroniği"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Ofis"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Aksesuar"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Oyun & Hobi"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Ev Aletleri"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Spor & Outdoor"
                        });
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Name = "TeoriV2-106687_large.jpg",
                            ProductId = 100,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HP/thumb/TeoriV2-106687_large.jpg"
                        },
                        new
                        {
                            Id = 101,
                            Name = "TeoriV2-97788_large.jpg",
                            ProductId = 101,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/LENOVO/thumb/TeoriV2-97788_large.jpg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "TeoriV2-106613_large.jpg",
                            ProductId = 102,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HUAWEI/thumb/TeoriV2-106613_large.jpg"
                        },
                        new
                        {
                            Id = 103,
                            Name = "TeoriV2-105445-7_large.jpg",
                            ProductId = 103,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ASUS/thumb/TeoriV2-105445-7_large.jpg"
                        },
                        new
                        {
                            Id = 104,
                            Name = "TeoriV2-106597_large.jpg",
                            ProductId = 104,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-106597_large.jpg"
                        },
                        new
                        {
                            Id = 105,
                            Name = "TeoriV2-105271-4_large.jpg",
                            ProductId = 105,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/APPLE/thumb/TeoriV2-105271-4_large.jpg"
                        },
                        new
                        {
                            Id = 106,
                            Name = "TeoriV2-105813_large.jpg",
                            ProductId = 106,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-105813_large.jpg"
                        },
                        new
                        {
                            Id = 107,
                            Name = "TeoriV2-105818-5_large.jpg",
                            ProductId = 107,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-105818-5_large.jpg"
                        },
                        new
                        {
                            Id = 108,
                            Name = "TeoriV2-105819-5_large.jpg",
                            ProductId = 108,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-105819-5_large.jpg"
                        },
                        new
                        {
                            Id = 109,
                            Name = "TeoriV2-105816-5_large.jpg",
                            ProductId = 109,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-105816-5_large.jpg"
                        },
                        new
                        {
                            Id = 110,
                            Name = "TeoriV2-106687_large.jpg",
                            ProductId = 110,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HP/thumb/TeoriV2-106687_large.jpg"
                        },
                        new
                        {
                            Id = 111,
                            Name = "TeoriV2-106598_large.jpg",
                            ProductId = 111,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ASUS/thumb/TeoriV2-106598_large.jpg"
                        },
                        new
                        {
                            Id = 112,
                            Name = "TeoriV2-106595_large.jpg",
                            ProductId = 112,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HP/thumb/TeoriV2-106595_large.jpg"
                        },
                        new
                        {
                            Id = 113,
                            Name = "TeoriV2-106571_large.jpg",
                            ProductId = 113,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HP/thumb/TeoriV2-106571_large.jpg"
                        },
                        new
                        {
                            Id = 114,
                            Name = "TeoriV2-106470_large.jpg",
                            ProductId = 114,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HP/thumb/TeoriV2-106470_large.jpg"
                        },
                        new
                        {
                            Id = 115,
                            Name = "TeoriV2-106421_large.jpg",
                            ProductId = 115,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/ACER/thumb/TeoriV2-106421_large.jpg"
                        },
                        new
                        {
                            Id = 116,
                            Name = "TeoriV2-104849_large.jpg",
                            ProductId = 116,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/DELL/thumb/TeoriV2-104849_large.jpg"
                        },
                        new
                        {
                            Id = 117,
                            Name = "TeoriV2-104680-3_large.jpg",
                            ProductId = 117,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HOMETECH/thumb/TeoriV2-104680-3_large.jpg"
                        },
                        new
                        {
                            Id = 118,
                            Name = "v2-92892_large.jpg",
                            ProductId = 118,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/DELL/thumb/v2-92892_large.jpg"
                        },
                        new
                        {
                            Id = 119,
                            Name = "TeoriV2-104849_large.jpg",
                            ProductId = 119,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/DELL/thumb/TeoriV2-104849_large.jpg"
                        },
                        new
                        {
                            Id = 120,
                            Name = "TeoriV2-106613_large.jpg",
                            ProductId = 120,
                            Url = "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/HUAWEI/thumb/TeoriV2-106613_large.jpg"
                        });
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("KargoFiyatı")
                        .HasColumnType("REAL");

                    b.Property<byte>("Marka")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int>("NumberInStock")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PreviousCost")
                        .HasColumnType("REAL");

                    b.Property<byte>("Tag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToplamSiparisSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CategoryId = 101,
                            Cost = 5049.0,
                            Info = "HP 15 - DA1021NT CORE İ5 8265U 1.6GHZ - 8GB - 256GB SSD - 15.6-MX110 2GB-W10 NOTEBOOK",
                            KargoFiyatı = 0.0,
                            Marka = (byte)8,
                            Name = "5QS63EA",
                            NumberInStock = 15,
                            PreviousCost = 4837.0,
                            Tag = (byte)1,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/hp-15-da1021nt-core-i5-8265u-1-6ghz-8gb-256gb-ssd-15-6-mx110-2gb-w10-notebook.html"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 101,
                            Cost = 6899.0,
                            Info = "LENOVO IDEAPAD S540 CORE İ5 10210U 1.6GHZ-8GB RAM-256GB SSD-15.6''-MX250 2GB-W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)1,
                            Name = "81ND009TTX",
                            NumberInStock = 9,
                            PreviousCost = 6593.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/lenovo-ideapad-s540-core-i5-10210u-1-6ghz-8gb-ram-256gb-ssd-15-6-mx250-2gb-w10.html"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 101,
                            Cost = 4599.0,
                            Info = "HUAWEI MATEBOOK D 15 AMD RYZEN 5 3500U 2.1GHZ-8GB-256GB SSD-15.6' - AMD - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)7,
                            Name = "53010TTJ",
                            NumberInStock = 10,
                            PreviousCost = 4395.0,
                            Tag = (byte)1,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/huawei-matebook-d-15-amd-ryzen-5-3500u-2-1ghz-8gb-512gbssd-15-6-amd-w10.html"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 101,
                            Cost = 4813.0,
                            Info = "ASUS X509FB CORE İ5 8265U 1.6GHZ-8GB RAM-256GB SSD-15.6' - MX110 2GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)6,
                            Name = "X509FB-BR073T",
                            NumberInStock = 8,
                            PreviousCost = 5000.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/asus-x509fb-core-i5-8265u-1-6ghz-8gb-ram-256gb-ssd-15-6-mx110-2gb-w10.html"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 101,
                            Cost = 4599.0,
                            Info = "ACER ASPIRE 3 CORE İ5 10210U 1.6GHZ-8GB-256GB SSD-15.6' - MX230 2GB - W10 NOTEBOOK",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "A315-55G-57HC",
                            NumberInStock = 15,
                            PreviousCost = 5000.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-aspire-3-core-i5-10210u-1-6ghz-8gb-256gb-ssd-15-6-mx230-2gb-w10-notebook.html"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 101,
                            Cost = 21499.0,
                            Info = "MACBOOK PRO TOUCH BAR CORE İ9 2.3GHZ-16GB-1TB SSD-RETINA 16' - 4GB - SILVER",
                            KargoFiyatı = 0.0,
                            Marka = (byte)5,
                            Name = "MVVM2TU/A",
                            NumberInStock = 3,
                            PreviousCost = 21800.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/macbook-pro-touch-bar-core-i9-2-3ghz-16gb-1tb-ssd-retina-16-4gb-silver.html"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 101,
                            Cost = 2299.0,
                            Info = "ACER ASPIRE 3 CELERON N4000 1.1GHZ-4GB RAM-128GB SSD-15.6' - INT - W10 NOTEBOOK",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "A315-34-C7LB",
                            NumberInStock = 35,
                            PreviousCost = 2500.0,
                            Tag = (byte)1,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-aspire-3-celeron-n4000-1-1ghz-4gb-ram-128gb-ssd-15-6-int-w10-notebook.html"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 101,
                            Cost = 10399.0,
                            Info = "ACER NITRO 5 CORE İ7 9750H 2.6GHZ-16GB-1TB+128GB SSD-15.6' - GTX1660TI 6GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "AN515-54-74XH",
                            NumberInStock = 5,
                            PreviousCost = 11000.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-nitro-5-core-i7-9750h-2-6ghz-16gb-1tb-128gb-ssd-15-6-gtx1660ti-6gb-w10.html"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 101,
                            Cost = 6299.0,
                            Info = "ACER NITRO 5 CORE İ5 8300H 2.3GHZ-8GB-1TB+128GB SSD-15.6' - GTX1050 3GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "AN515-54-56UW",
                            NumberInStock = 12,
                            PreviousCost = 6700.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-nitro-5-core-i5-8300h-2-3ghz-8gb-1tb-128gb-ssd-15-6-gtx1050-3gb-w10.html"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 101,
                            Cost = 8999.0,
                            Info = "ACER NITRO 5 CORE İ7 9750H 2.6GHZ-16GB-1TB+256GB SSD-15.6' - GTX1650 4GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "AN515-54-78JD",
                            NumberInStock = 12,
                            PreviousCost = 9105.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-nitro-5-core-i7-9750h-2-6ghz-16gb-1tb-256gb-ssd-15-6-gtx1650-4gb-w10.html"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 101,
                            Cost = 5049.0,
                            Info = "HP 15-DA1021NT CORE İ5 8265U 1.6GHZ-8GB-256GB SSD-15.6' - MX110 2GB - W10 NOTEBOOK",
                            KargoFiyatı = 0.0,
                            Marka = (byte)8,
                            Name = "5QS63EA",
                            NumberInStock = 11,
                            PreviousCost = 5500.0,
                            Tag = (byte)1,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/hp-15-da1021nt-core-i5-8265u-1-6ghz-8gb-256gb-ssd-15-6-mx110-2gb-w10-notebook.html"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 101,
                            Cost = 10028.0,
                            Info = "ASUS G531GT CORE İ7 9750H 2.6GHZ-16GB-512GB SSD-15.6''-GTX1650 4GB-W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)2,
                            Name = "G531GT-AL178T-Gaming",
                            NumberInStock = 2,
                            PreviousCost = 10050.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/asus-g531gt-core-i7-9750h-2-6ghz-16gb-512gb-ssd-15-6-gtx1650-4gb-w10.html"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 101,
                            Cost = 12499.0,
                            Info = "HP SPECTRE X360 13-AW0001NT CORE İ7 1065G7 1.3GHZ-16GB-512GB SSD-13.3' - INT - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)8,
                            Name = "7WA87EA",
                            NumberInStock = 8,
                            PreviousCost = 14299.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/hp-spectre-x360-13-aw0001nt-core-i7-1065g7-1-3ghz-16gb-512gb-ssd-13-3-int-w10.html"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 101,
                            Cost = 5599.0,
                            Info = "HP 15-DA1116NT CORE İ5 8265U 1.6GHZ-8GB-1TB+128GB SSD-15.6' - MX110 2GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)8,
                            Name = "9QH75EA",
                            NumberInStock = 35,
                            PreviousCost = 5300.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/hp-15-da1116nt-core-i5-8265u-1-6ghz-8gb-1tb-128gb-ssd-15-6-mx110-2gb-w10.html"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 101,
                            Cost = 4949.0,
                            Info = "HP 15-DA1065NT CORE İ5 8265U 1.6GHZ-4GB-128GB SSD-15.6' - MX110 2GB - W10 NOTEBOOK",
                            KargoFiyatı = 0.0,
                            Marka = (byte)8,
                            Name = "6TC05EA",
                            NumberInStock = 50,
                            PreviousCost = 4725.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/hp-15-da1065nt-core-i5-8265u-1-6ghz-4gb-128gb-ssd-15-6-mx110-2gb-w10-notebook.html"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 101,
                            Cost = 5799.0,
                            Info = "ACER SWIFT 3 AMD RYZEN 7 3700U 2.3GHZ-8GB-256GB SSD-14' - RX540 2GB - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)4,
                            Name = "SF314-41G-R1WG",
                            NumberInStock = 50,
                            PreviousCost = 5700.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/acer-swift-3-amd-ryzen-7-3700u-2-3ghz-8gb-256gb-ssd-14-rx540-2gb-w10.html"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 101,
                            Cost = 9686.0,
                            Info = "DELL G315 CORE İ7 9750H 2.6GHZ-16GB -1TB+256 SSD-GTX1650 4GB-15.6'W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)6,
                            Name = "G315-4B75D256W161C",
                            NumberInStock = 8,
                            PreviousCost = 9686.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/dell-g315-core-i7-9750h-2-6ghz-16gb-1tb-256-ssd-gtx1650-4gb-15-6-w10.html"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 101,
                            Cost = 2299.0,
                            Info = "HOMETECH ALFA 300i INTEL CORE İ3 5005U 2GHZ-4GB-128GB SSD-14''INT-W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)9,
                            Name = "31.8029",
                            NumberInStock = 35,
                            PreviousCost = 2500.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 1,
                            Url = "https://www.vatanbilgisayar.com/hometech-alfa-300i-intel-core-i3-5005u-2ghz-4gb-128gb-ssd-14-int-w10.html"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 101,
                            Cost = 11697.0,
                            Info = "DELL G317 CORE İ7 8750H 2.2GHZ-16GB -2TB+256 SSD-GTX1060 6GB-17.3'W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)6,
                            Name = "G317-FB75D256W162C",
                            NumberInStock = 12,
                            PreviousCost = 11000.0,
                            Tag = (byte)2,
                            ToplamSiparisSayisi = 1,
                            Url = "https://www.vatanbilgisayar.com/dell-g317-core-i7-8750h-2-2ghz-16gb-2tb-256-ssd-gtx1060-6gb-17-3-w10.html"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 101,
                            Cost = 9686.0,
                            Info = "DELL G315 CORE İ7 9750H 2.6GHZ-16GB -1TB+256 SSD-GTX1650 4GB-15.6'W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)6,
                            Name = "G315-4B75D256W161C",
                            NumberInStock = 18,
                            PreviousCost = 9700.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/dell-g315-core-i7-9750h-2-6ghz-16gb-1tb-256-ssd-gtx1650-4gb-15-6-w10.html"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 101,
                            Cost = 4599.0,
                            Info = "HUAWEI MATEBOOK D 15 AMD RYZEN 5 3500U 2.1GHZ-8GB-256GB SSD-15.6' - AMD - W10",
                            KargoFiyatı = 0.0,
                            Marka = (byte)7,
                            Name = "53010TTJ",
                            NumberInStock = 35,
                            PreviousCost = 4680.0,
                            Tag = (byte)3,
                            ToplamSiparisSayisi = 0,
                            Url = "https://www.vatanbilgisayar.com/huawei-matebook-d-15-amd-ryzen-5-3500u-2-1ghz-8gb-512gbssd-15-6-amd-w10.html"
                        });
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Sepet", b =>
                {
                    b.Property<int>("SepetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SepeteKonulmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SepetId");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserId");

                    b.ToTable("Sepet");

                    b.HasData(
                        new
                        {
                            SepetId = 1,
                            Adet = 1,
                            ProductID = 117,
                            SepeteKonulmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            SepetId = 2,
                            Adet = 1,
                            ProductID = 118,
                            SepeteKonulmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Adet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SiparisId");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserId");

                    b.ToTable("Siparis");

                    b.HasData(
                        new
                        {
                            SiparisId = 1,
                            Adet = 1,
                            ProductID = 117,
                            SiparisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            SiparisId = 2,
                            Adet = 1,
                            ProductID = 118,
                            SiparisTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("VatanAPI.Core.Models.UserRole", b =>
                {
                    b.HasOne("VatanAPI.Core.Models.Role", "Role")
                        .WithMany("UsersRole")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VatanAPI.Core.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Image", b =>
                {
                    b.HasOne("VatanAPI.Domain.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Product", b =>
                {
                    b.HasOne("VatanAPI.Domain.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Sepet", b =>
                {
                    b.HasOne("VatanAPI.Domain.Models.Product", "Product")
                        .WithMany("Sepetler")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VatanAPI.Core.Models.User", "User")
                        .WithMany("Sepetler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VatanAPI.Domain.Models.Siparis", b =>
                {
                    b.HasOne("VatanAPI.Domain.Models.Product", "Product")
                        .WithMany("Siparisler")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VatanAPI.Core.Models.User", "User")
                        .WithMany("Siparisler")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
